"use client";

import React, { useState, useEffect, useCallback } from "react";
import { FaTimes, FaSpinner, FaCalendarAlt, FaEye } from "react-icons/fa";
import Image from "next/image";

interface AttendanceRecord {
  _id: string;
  employeeId: string;
  date: string;
  punchInTime: string;
  punchOutTime?: string;
  punchInPhoto?: string;
  punchOutPhoto?: string;
  punchInLatitude?: number;
  punchInLongitude?: number;
  punchOutLatitude?: number;
  punchOutLongitude?: number;
  status: string;
  attendanceType: string;
  projectName?: string;
  designation?: string;
  isAutoGenerated: boolean;
  isRegularized: boolean;
  regularizationStatus?: string;
}

// Removed unused AttendanceData interface

interface LeaveHistoryItem {
  leaveId: string;
  employeeName: string;
  leaveType: string;
  startDate: string;
  endDate: string;
  numberOfDays: number;
  isHalfDay: boolean;
  halfDayType: string | null;
  status: string;
  reason: string;
  emergencyContact: string;
  attachments: unknown[];
  appliedOn: string;
  lastUpdated: string;
  approvalDate?: string;
  approvedBy?: string;
  rejectionReason?: string;
}

interface LeaveBalances {
  EL: number;
  CL: number;
  SL: number;
  CompOff: number;
}

interface LeaveData {
  employeeId: string;
  employeeName: string;
  totalLeaves: number;
  leaveBalances: LeaveBalances;
  leaveHistory: LeaveHistoryItem[];
}

interface AttendanceModalProps {
  isOpen: boolean;
  onClose: () => void;
  employeeId: string;
  employeeName: string;
  theme: "dark" | "light";
}

const AttendanceModal: React.FC<AttendanceModalProps> = ({ isOpen, onClose, employeeId, employeeName, theme }) => {
  const [activeTab, setActiveTab] = useState<'attendance' | 'leave'>('attendance');
  const [attendanceData, setAttendanceData] = useState<AttendanceRecord[]>([]);
  const [leaveData, setLeaveData] = useState<LeaveData | null>(null);
  const [loading, setLoading] = useState(false);
  const [leaveLoading, setLeaveLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [leaveError, setLeaveError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'monthly' | 'daterange'>('monthly');
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [selectedRecord, setSelectedRecord] = useState<AttendanceRecord | null>(null);
  const [selectedLeave, setSelectedLeave] = useState<LeaveHistoryItem | null>(null);
  const [showDetailModal, setShowDetailModal] = useState(false);
  const [showLeaveDetailModal, setShowLeaveDetailModal] = useState(false);
  const [punchInAddress, setPunchInAddress] = useState('');
  const [punchOutAddress, setPunchOutAddress] = useState('');

  const fetchAttendanceData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      let url = '';
      if (viewMode === 'monthly') {
        url = `https://cafm.zenapi.co.in/api/attendance/report/monthly/employee?employeeId=${employeeId}&month=${selectedMonth}&year=${selectedYear}`;
      } else {
        if (!fromDate || !toDate) {
          setError('Please select both from and to dates');
          return;
        }
        // For date range, fetch all attendance data and filter client-side
        url = `https://cafm.zenapi.co.in/api/attendance/all`;
      }
      
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`Failed to fetch attendance data: ${response.status} ${response.statusText}`);
      }
      const result = await response.json();
      
      // Debug logging
      console.log('API Response:', result);
      console.log('View Mode:', viewMode);
      console.log('Employee ID:', employeeId);
      console.log('From Date:', fromDate);
      console.log('To Date:', toDate);
      
      let filteredData = result.attendance || [];
      
      // If date range mode, filter by employee and date range
      if (viewMode === 'daterange') {
        filteredData = filteredData.filter((record: AttendanceRecord) => {
          // Filter by employee ID
          if (record.employeeId !== employeeId) return false;
          
          // Filter by date range - normalize dates to compare only date parts
          const recordDate = new Date(record.date);
          const from = new Date(fromDate + 'T00:00:00');
          const to = new Date(toDate + 'T23:59:59');
          
          return recordDate >= from && recordDate <= to;
        });
      }
      
      console.log('Filtered Data:', filteredData);
      setAttendanceData(filteredData);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  }, [employeeId, selectedMonth, selectedYear, fromDate, toDate, viewMode]);

  const fetchLeaveData = useCallback(async () => {
    setLeaveLoading(true);
    setLeaveError(null);
    try {
      const response = await fetch(`https://cafm.zenapi.co.in/api/leave/history/${employeeId}`);
      if (!response.ok) {
        throw new Error(`Failed to fetch leave history: ${response.status} ${response.statusText}`);
      }
      const result = await response.json();
      setLeaveData(result);
    } catch (err) {
      setLeaveError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLeaveLoading(false);
    }
  }, [employeeId]);

  useEffect(() => {
    if (isOpen && employeeId) {
      if (activeTab === 'attendance') {
        fetchAttendanceData();
      } else if (activeTab === 'leave') {
        fetchLeaveData();
      }
    }
  }, [isOpen, employeeId, activeTab, selectedMonth, selectedYear, fromDate, toDate, fetchAttendanceData, fetchLeaveData]);

  const reverseGeocode = async (lat: number, lng: number): Promise<string> => {
    if (!lat || !lng || isNaN(lat) || isNaN(lng)) return '';
    try {
      const url = `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lng}&addressdetails=1&accept-language=en&zoom=18`;
      const response = await fetch(url, { headers: { 'User-Agent': 'EmployeeManagementApp/1.0' } });
      if (!response.ok) return '';
      const data = await response.json();
      return data.display_name || '';
    } catch {
      return '';
    }
  };

  const handleViewDetails = async (record: AttendanceRecord) => {
    setSelectedRecord(record);
    setShowDetailModal(true);
    
    // Get addresses
    let punchInAddr = '';
    let punchOutAddr = '';
    
    if (record.punchInLatitude && record.punchInLongitude) {
      punchInAddr = await reverseGeocode(record.punchInLatitude, record.punchInLongitude);
    }
    if (record.punchOutLatitude && record.punchOutLongitude) {
      punchOutAddr = await reverseGeocode(record.punchOutLatitude, record.punchOutLongitude);
    }
    
    setPunchInAddress(punchInAddr);
    setPunchOutAddress(punchOutAddr);
  };

  const getStatusColor = (status: string) => {
    switch (status.toLowerCase()) {
      case 'present':
        return 'bg-green-100 text-green-800';
      case 'absent':
        return 'bg-red-100 text-red-800';
      case 'late':
        return 'bg-yellow-100 text-yellow-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const getLeaveStatusColor = (status: string) => {
    switch (status.toLowerCase()) {
      case 'approved':
        return 'bg-green-100 text-green-800';
      case 'pending':
        return 'bg-yellow-100 text-yellow-800';
      case 'rejected':
        return 'bg-red-100 text-red-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const getLeaveTypeColor = (leaveType: string) => {
    switch (leaveType) {
      case 'EL':
        return 'bg-blue-100 text-blue-800';
      case 'CL':
        return 'bg-purple-100 text-purple-800';
      case 'SL':
        return 'bg-orange-100 text-orange-800';
      case 'CompOff':
        return 'bg-teal-100 text-teal-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const handleViewLeaveDetails = (leave: LeaveHistoryItem) => {
    setSelectedLeave(leave);
    setShowLeaveDetailModal(true);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-60 p-4 backdrop-blur-sm">
      <div
        className={`rounded-lg shadow-lg max-w-6xl w-full max-h-[90vh] overflow-hidden ${
          theme === "dark" ? "bg-gray-900" : "bg-white"
        }`}
      >
        {/* Header */}
        <div className={`p-4 border-b ${theme === "dark" ? "border-gray-700" : "border-gray-200"}`}>
          <div className="flex justify-between items-center mb-4">
            <div>
              <h2 className={`text-xl font-bold ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                Employee Records
              </h2>
              <p className={`text-sm ${theme === "dark" ? "text-gray-300" : "text-gray-600"}`}>
                {employeeName} ({employeeId})
              </p>
            </div>
            <button
              onClick={onClose}
              className={`text-xl ${theme === "dark" ? "text-gray-400 hover:text-gray-200" : "text-gray-400 hover:text-gray-700"}`}
            >
              <FaTimes />
            </button>
          </div>
          
          {/* Tabs */}
          <div className="flex space-x-1">
            <button
              onClick={() => setActiveTab('attendance')}
              className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                activeTab === 'attendance'
                  ? theme === "dark"
                    ? "bg-blue-600 text-white"
                    : "bg-blue-500 text-white"
                  : theme === "dark"
                  ? "text-gray-400 hover:text-white hover:bg-gray-800"
                  : "text-gray-600 hover:text-gray-900 hover:bg-gray-100"
              }`}
            >
              <FaCalendarAlt className="inline mr-2" />
              Attendance
            </button>
            <button
              onClick={() => setActiveTab('leave')}
              className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                activeTab === 'leave'
                  ? theme === "dark"
                    ? "bg-blue-600 text-white"
                    : "bg-blue-500 text-white"
                  : theme === "dark"
                  ? "text-gray-400 hover:text-white hover:bg-gray-800"
                  : "text-gray-600 hover:text-gray-900 hover:bg-gray-100"
              }`}
            >
              <FaEye className="inline mr-2" />
              Leave
            </button>
          </div>
        </div>

        {/* Filters - Only show for attendance tab */}
        {activeTab === 'attendance' && (
          <div className={`p-4 border-b ${theme === "dark" ? "border-gray-700" : "border-gray-200"}`}>
          <div className="flex flex-wrap gap-4 items-center">
            <div className="flex gap-2">
              <button
                onClick={() => setViewMode('monthly')}
                className={`px-3 py-1 rounded text-sm ${
                  viewMode === 'monthly'
                    ? 'bg-blue-500 text-white'
                    : theme === 'dark' ? 'bg-gray-700 text-gray-300' : 'bg-gray-200 text-gray-700'
                }`}
              >
                Monthly
              </button>
              <button
                onClick={() => setViewMode('daterange')}
                className={`px-3 py-1 rounded text-sm ${
                  viewMode === 'daterange'
                    ? 'bg-blue-500 text-white'
                    : theme === 'dark' ? 'bg-gray-700 text-gray-300' : 'bg-gray-200 text-gray-700'
                }`}
              >
                Date Range
              </button>
            </div>

            {viewMode === 'monthly' ? (
              <div className="flex gap-2 items-center">
                <select
                  value={selectedMonth}
                  onChange={(e) => setSelectedMonth(Number(e.target.value))}
                  className={`px-2 py-1 border rounded text-sm ${
                    theme === "dark" ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300 text-gray-900"
                  }`}
                >
                  {Array.from({ length: 12 }, (_, i) => (
                    <option key={i + 1} value={i + 1}>
                      {new Date(0, i).toLocaleString('default', { month: 'long' })}
                    </option>
                  ))}
                </select>
                <select
                  value={selectedYear}
                  onChange={(e) => setSelectedYear(Number(e.target.value))}
                  className={`px-2 py-1 border rounded text-sm ${
                    theme === "dark" ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300 text-gray-900"
                  }`}
                >
                  {Array.from({ length: 5 }, (_, i) => {
                    const year = new Date().getFullYear() - 2 + i;
                    return <option key={year} value={year}>{year}</option>;
                  })}
                </select>
              </div>
            ) : (
              <div className="flex gap-2 items-center">
                <input
                  type="date"
                  value={fromDate}
                  onChange={(e) => setFromDate(e.target.value)}
                  className={`px-2 py-1 border rounded text-sm ${
                    theme === "dark" ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300 text-gray-900"
                  }`}
                />
                <span className={`text-sm ${theme === "dark" ? "text-gray-300" : "text-gray-600"}`}>to</span>
                <input
                  type="date"
                  value={toDate}
                  onChange={(e) => setToDate(e.target.value)}
                  className={`px-2 py-1 border rounded text-sm ${
                    theme === "dark" ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300 text-gray-900"
                  }`}
                />
              </div>
            )}

            <button
              onClick={fetchAttendanceData}
              className={`px-4 py-1 rounded text-sm ${
                theme === "dark" ? "bg-blue-600 text-white hover:bg-blue-700" : "bg-blue-500 text-white hover:bg-blue-600"
              }`}
            >
              <FaCalendarAlt className="inline mr-1" />
              Load Data
            </button>
          </div>
          </div>
        )}

        {/* Content */}
        <div className="overflow-auto max-h-[calc(90vh-200px)]">
          {activeTab === 'attendance' ? (
            // Attendance Tab Content
            loading ? (
              <div className="flex items-center justify-center py-12">
                <FaSpinner className="animate-spin text-xl text-blue-500 mr-3" />
                <span className={`text-lg ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                  Loading attendance data...
                </span>
              </div>
            ) : error ? (
              <div className="text-center py-12">
                <div className="text-red-500 text-lg font-semibold mb-2">Error</div>
                <div className={`text-sm ${theme === "dark" ? "text-gray-300" : "text-gray-600"}`}>
                  {error}
                </div>
                <button
                  onClick={fetchAttendanceData}
                  className="mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                >
                  Retry
                </button>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className={`w-full text-sm border-collapse ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                  <thead className={`${theme === "dark" ? "bg-gray-800" : "bg-gray-50"}`}>
                    <tr>
                      <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                        Date
                      </th>
                      <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                        Punch In
                      </th>
                      <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                        Punch Out
                      </th>
                      <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                        Status
                      </th>
                      <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                        Type
                      </th>
                      <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {attendanceData.length === 0 ? (
                      <tr>
                        <td colSpan={6} className={`px-3 py-8 text-center ${theme === "dark" ? "text-gray-400" : "text-gray-500"}`}>
                          No attendance records found
                        </td>
                      </tr>
                    ) : (
                      attendanceData.map((record) => (
                        <tr key={record._id} className={`border-b ${theme === "dark" ? "border-gray-700 hover:bg-gray-800" : "border-gray-200 hover:bg-gray-50"}`}>
                          <td className={`px-3 py-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                            {new Date(record.date).toLocaleDateString()}
                          </td>
                          <td className={`px-3 py-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                            {record.punchInTime ? new Date(record.punchInTime).toLocaleTimeString() : '-'}
                          </td>
                          <td className={`px-3 py-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                            {record.punchOutTime ? new Date(record.punchOutTime).toLocaleTimeString() : '-'}
                          </td>
                          <td className={`px-3 py-2`}>
                            <span className={`text-xs px-2 py-1 rounded ${getStatusColor(record.status)}`}>
                              {record.status}
                            </span>
                          </td>
                          <td className={`px-3 py-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                            {record.attendanceType}
                          </td>
                          <td className={`px-3 py-2`}>
                            <button
                              onClick={() => handleViewDetails(record)}
                              className={`px-3 py-1 rounded text-xs ${
                                theme === "dark" ? "bg-blue-600 text-white hover:bg-blue-700" : "bg-blue-500 text-white hover:bg-blue-600"
                              }`}
                            >
                              View Details
                            </button>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            )
          ) : (
            // Leave Tab Content
            leaveLoading ? (
              <div className="flex items-center justify-center py-12">
                <FaSpinner className="animate-spin text-xl text-blue-500 mr-3" />
                <span className={`text-lg ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                  Loading leave data...
                </span>
              </div>
            ) : leaveError ? (
              <div className="text-center py-12">
                <div className="text-red-500 text-lg font-semibold mb-2">Error</div>
                <div className={`text-sm ${theme === "dark" ? "text-gray-300" : "text-gray-600"}`}>
                  {leaveError}
                </div>
                <button
                  onClick={fetchLeaveData}
                  className="mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                >
                  Retry
                </button>
              </div>
            ) : leaveData ? (
              <div className="p-4 space-y-6">
                {/* Leave Balances Summary */}
                <div className={`p-4 rounded-lg ${theme === "dark" ? "bg-gray-800" : "bg-gray-50"}`}>
                  <h3 className={`text-lg font-semibold mb-3 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                    Leave Balances
                  </h3>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div className="text-center">
                      <div className={`text-2xl font-bold ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                        {leaveData.leaveBalances.EL}
                      </div>
                      <div className={`text-sm ${theme === "dark" ? "text-gray-300" : "text-gray-600"}`}>
                        Earned Leave (EL)
                      </div>
                    </div>
                    <div className="text-center">
                      <div className={`text-2xl font-bold ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                        {leaveData.leaveBalances.CL}
                      </div>
                      <div className={`text-sm ${theme === "dark" ? "text-gray-300" : "text-gray-600"}`}>
                        Casual Leave (CL)
                      </div>
                    </div>
                    <div className="text-center">
                      <div className={`text-2xl font-bold ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                        {leaveData.leaveBalances.SL}
                      </div>
                      <div className={`text-sm ${theme === "dark" ? "text-gray-300" : "text-gray-600"}`}>
                        Sick Leave (SL)
                      </div>
                    </div>
                    <div className="text-center">
                      <div className={`text-2xl font-bold ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                        {leaveData.leaveBalances.CompOff}
                      </div>
                      <div className={`text-sm ${theme === "dark" ? "text-gray-300" : "text-gray-600"}`}>
                        Comp Off
                      </div>
                    </div>
                  </div>
                </div>

                {/* Leave History Table */}
                <div className="overflow-x-auto">
                  <table className={`w-full text-sm border-collapse ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                    <thead className={`${theme === "dark" ? "bg-gray-800" : "bg-gray-50"}`}>
                      <tr>
                        <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                          Leave Type
                        </th>
                        <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                          Start Date
                        </th>
                        <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                          End Date
                        </th>
                        <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                          Days
                        </th>
                        <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                          Half Day
                        </th>
                        <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                          Status
                        </th>
                        <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                          Applied On
                        </th>
                        <th className={`px-3 py-2 text-left font-semibold border-b ${theme === "dark" ? "border-gray-700 text-gray-200" : "border-gray-200 text-gray-700"}`}>
                          Actions
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {leaveData.leaveHistory.length === 0 ? (
                        <tr>
                          <td colSpan={8} className={`px-3 py-8 text-center ${theme === "dark" ? "text-gray-400" : "text-gray-500"}`}>
                            No leave records found
                          </td>
                        </tr>
                      ) : (
                        leaveData.leaveHistory.map((leave) => (
                          <tr key={leave.leaveId} className={`border-b ${theme === "dark" ? "border-gray-700 hover:bg-gray-800" : "border-gray-200 hover:bg-gray-50"}`}>
                            <td className={`px-3 py-2`}>
                              <span className={`text-xs px-2 py-1 rounded ${getLeaveTypeColor(leave.leaveType)}`}>
                                {leave.leaveType}
                              </span>
                            </td>
                            <td className={`px-3 py-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                              {new Date(leave.startDate).toLocaleDateString()}
                            </td>
                            <td className={`px-3 py-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                              {new Date(leave.endDate).toLocaleDateString()}
                            </td>
                            <td className={`px-3 py-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                              {leave.numberOfDays}
                            </td>
                            <td className={`px-3 py-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                              {leave.isHalfDay ? leave.halfDayType || 'Half Day' : 'Full Day'}
                            </td>
                            <td className={`px-3 py-2`}>
                              <span className={`text-xs px-2 py-1 rounded ${getLeaveStatusColor(leave.status)}`}>
                                {leave.status}
                              </span>
                            </td>
                            <td className={`px-3 py-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                              {new Date(leave.appliedOn).toLocaleDateString()}
                            </td>
                            <td className={`px-3 py-2`}>
                              <button
                                onClick={() => handleViewLeaveDetails(leave)}
                                className={`px-3 py-1 rounded text-xs ${
                                  theme === "dark" ? "bg-blue-600 text-white hover:bg-blue-700" : "bg-blue-500 text-white hover:bg-blue-600"
                                }`}
                              >
                                <FaEye className="inline mr-1" />
                                View
                              </button>
                            </td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            ) : null
          )}
        </div>

        {/* Footer */}
        <div className={`p-4 border-t ${theme === "dark" ? "border-gray-700" : "border-gray-200"}`}>
          <div className="flex justify-end">
            <button
              onClick={onClose}
              className={`px-4 py-2 rounded font-semibold ${
                theme === "dark"
                  ? "bg-gray-700 text-white hover:bg-gray-600"
                  : "bg-white text-gray-800 hover:bg-gray-100 border border-gray-300"
              }`}
            >
              Close
            </button>
          </div>
        </div>
      </div>

      {/* Detail Modal */}
      {showDetailModal && selectedRecord && (
        <div className="fixed inset-0 z-60 flex items-center justify-center bg-black bg-opacity-60 p-4 backdrop-blur-sm">
          <div className={`rounded-lg shadow-lg max-w-4xl w-full max-h-[90vh] overflow-hidden ${
            theme === "dark" ? "bg-gray-900" : "bg-white"
          }`}>
            <div className={`p-4 border-b ${theme === "dark" ? "border-gray-700" : "border-gray-200"}`}>
              <div className="flex justify-between items-center">
                <h3 className={`text-lg font-bold ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                  Attendance Details
                </h3>
                <button
                  onClick={() => setShowDetailModal(false)}
                  className={`text-xl ${theme === "dark" ? "text-gray-400 hover:text-gray-200" : "text-gray-400 hover:text-gray-700"}`}
                >
                  <FaTimes />
                </button>
              </div>
            </div>
            
            <div className="p-4 overflow-auto max-h-[calc(90vh-120px)]">
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div><strong>Date:</strong> {new Date(selectedRecord.date).toLocaleDateString()}</div>
                <div><strong>Status:</strong> {selectedRecord.status}</div>
                <div><strong>Type:</strong> {selectedRecord.attendanceType}</div>
                <div><strong>Project:</strong> {selectedRecord.projectName || '-'}</div>
                <div><strong>Punch In:</strong> {selectedRecord.punchInTime ? new Date(selectedRecord.punchInTime).toLocaleTimeString() : '-'}</div>
                <div><strong>Punch Out:</strong> {selectedRecord.punchOutTime ? new Date(selectedRecord.punchOutTime).toLocaleTimeString() : '-'}</div>
                <div className="col-span-2"><strong>Punch In Location:</strong> {punchInAddress || 'Location not available'}</div>
                <div className="col-span-2"><strong>Punch Out Location:</strong> {punchOutAddress || 'Location not available'}</div>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="text-sm font-semibold mb-2">Punch In Photo</div>
                  {selectedRecord.punchInPhoto ? (
                    <Image src={selectedRecord.punchInPhoto} alt="Punch In" width={200} height={250} className="rounded-lg w-48 h-60 object-cover" />
                  ) : (
                    <div className="w-48 h-60 rounded-lg bg-gray-200 flex items-center justify-center text-gray-400">No Photo</div>
                  )}
                </div>
                <div>
                  <div className="text-sm font-semibold mb-2">Punch Out Photo</div>
                  {selectedRecord.punchOutPhoto ? (
                    <Image src={selectedRecord.punchOutPhoto} alt="Punch Out" width={200} height={250} className="rounded-lg w-48 h-60 object-cover" />
                  ) : (
                    <div className="w-48 h-60 rounded-lg bg-gray-200 flex items-center justify-center text-gray-400">No Photo</div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Leave Detail Modal */}
      {showLeaveDetailModal && selectedLeave && (
        <div className="fixed inset-0 z-60 flex items-center justify-center bg-black bg-opacity-60 p-4 backdrop-blur-sm">
          <div className={`rounded-lg shadow-lg max-w-2xl w-full max-h-[90vh] overflow-hidden ${
            theme === "dark" ? "bg-gray-900" : "bg-white"
          }`}>
            <div className={`p-4 border-b ${theme === "dark" ? "border-gray-700" : "border-gray-200"}`}>
              <div className="flex justify-between items-center">
                <h3 className={`text-lg font-bold ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                  Leave Details
                </h3>
                <button
                  onClick={() => setShowLeaveDetailModal(false)}
                  className={`text-xl ${theme === "dark" ? "text-gray-400 hover:text-gray-200" : "text-gray-400 hover:text-gray-700"}`}
                >
                  <FaTimes />
                </button>
              </div>
            </div>
            
            <div className="p-4 overflow-auto max-h-[calc(90vh-120px)]">
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Leave Type:</strong>
                    <span className={`ml-2 px-2 py-1 rounded text-xs ${getLeaveTypeColor(selectedLeave.leaveType)}`}>
                      {selectedLeave.leaveType}
                    </span>
                  </div>
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Status:</strong>
                    <span className={`ml-2 px-2 py-1 rounded text-xs ${getLeaveStatusColor(selectedLeave.status)}`}>
                      {selectedLeave.status}
                    </span>
                  </div>
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Start Date:</strong>
                    <span className={`ml-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                      {new Date(selectedLeave.startDate).toLocaleDateString()}
                    </span>
                  </div>
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>End Date:</strong>
                    <span className={`ml-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                      {new Date(selectedLeave.endDate).toLocaleDateString()}
                    </span>
                  </div>
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Number of Days:</strong>
                    <span className={`ml-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                      {selectedLeave.numberOfDays}
                    </span>
                  </div>
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Half Day:</strong>
                    <span className={`ml-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                      {selectedLeave.isHalfDay ? selectedLeave.halfDayType || 'Half Day' : 'Full Day'}
                    </span>
                  </div>
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Applied On:</strong>
                    <span className={`ml-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                      {new Date(selectedLeave.appliedOn).toLocaleString()}
                    </span>
                  </div>
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Emergency Contact:</strong>
                    <span className={`ml-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                      {selectedLeave.emergencyContact}
                    </span>
                  </div>
                </div>
                
                <div>
                  <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Reason:</strong>
                  <div className={`mt-1 p-3 rounded ${theme === "dark" ? "bg-gray-800 text-white" : "bg-gray-50 text-gray-900"}`}>
                    {selectedLeave.reason}
                  </div>
                </div>

                {selectedLeave.approvalDate && (
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Approval Date:</strong>
                    <span className={`ml-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                      {new Date(selectedLeave.approvalDate).toLocaleString()}
                    </span>
                  </div>
                )}

                {selectedLeave.approvedBy && (
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Approved By:</strong>
                    <span className={`ml-2 ${theme === "dark" ? "text-white" : "text-gray-900"}`}>
                      {selectedLeave.approvedBy}
                    </span>
                  </div>
                )}

                {selectedLeave.rejectionReason && (
                  <div>
                    <strong className={`${theme === "dark" ? "text-gray-300" : "text-gray-700"}`}>Rejection Reason:</strong>
                    <div className={`mt-1 p-3 rounded ${theme === "dark" ? "bg-red-900 text-red-200" : "bg-red-50 text-red-800"}`}>
                      {selectedLeave.rejectionReason}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AttendanceModal;
